
const storyRand1 = "<div id='copy-output' class='w3-container w3-animate-zoom'><h2>Snow Storm</h2><br><p>Weather plays an important part in our __noun__ everyday. <br>What is weather you ask? <br>According to __adj__ scientists, who are known as meterologists, <br>weather is what the __noun__ is like at any time of the __noun__. <br> It doesn't matter if the air is __adj__ or __adj__, its all weather. <br>When vapors in __adj__ clouds condense, we have __noun__ and snow. <br>A lot of __noun__ means a __adj__ snowstorm!</p>"

const story01b = "<div id='copy-output' class='w3-container w3-animate-zoom'><h2>Snow Storm</h2><br><p>Weather plays an important part in our __noun__ everyday. <br>What is weather you ask? <br>According to __adj__ scientists, who are known as meterologists, <br>weather is what the __noun__ is like at any time of the __noun__. <br> It doesn't matter if the air is __adj__ or __adj__, its all weather. <br>When vapors in __adj__ clouds condense, we have __noun__ and snow. <br>A lot of __noun__ means a __adj__ snowstorm!</p>"

const storyRand2 = "<div id='copy-output' class='w3-container w3-animate-zoom'>We're playing Space Jam all night."

const story02b = "<div id='copy-output' class='w3-container w3-animate-zoom'>Golbledy-gook express, one ticket please."

const storyRand3 = "<div id='copy-output' class='w3-container w3-animate-zoom'>Please See Story Entitled: 'Ant Hill'"

const story03b = "<div id='copy-output' class='w3-container w3-animate-zoom'><h1>The Ant Hill</h1><h4>The little ant followed a string of ants along the ground towards the <button id='btn0301' class='w3-button w3-border-0' onclick='noun01'><i><u>noun</u></i></button>. <br>It was following a scent-marked path back home.<br>The <button id='adjbtn0301' class='w3-button w3-border-0' onclick='adjbtn0301()'><i><u>adjective</u></i></button> clouds loomed in the distance.<br>Suddenly, there came a <button id='adjbtn0301' class='w3-button w3-border-0' onclick='adjbtn0301()'><i><u>adjective</u></i></button> from the clouds. A storm was brewing!<br>The little <button id='btn0302' class='w3-button w3-border-0' onclick='noun01()'><i><u>noun(s)</i></u></button> must hurry if they are to make it inside!<br>The storm rushes in but the <button id='btn5' class='w3-button w3-border-0' onclick='noun01()'><i><u>noun</i></u></button> made it inside the hill and are safe for another day.</p></div>"
